### ISSUE TITLE
Web App

### ISSUE THREAD

**Issue by mtimkovich** [akbiggs/challonge-tools#25]
We should make a web interface using the Google App Engine™ to make these scripts more accessible.

**Comment by akbiggs** [comment]
I want to do this, but I think that the seeds tools (shuffle_seeds, garpr_seeds) rely on the Challonge API key belonging to an admin of the tournament. This is also how the amateur bracket gets created under the right Challonge account.

Any suggestions for how we could get around that?

**Comment by mtimkovich** [comment]
We could have sign ins, and users could add their API key as a setting.
