### ISSUE TITLE
Single command to seed tournament by garPR and then randomize it

### ISSUE THREAD

**Issue by ericslee** [akbiggs/challonge-tools#4]
Right now it seems like we have to run two commands to get a final seeded with Neal's randomization.
python garpr_seeds_challonge.py tourney100
python shuffle_seeds_challonge.py tourney100

would be convenient to have a command that runs one and then the other back to back. OR, (maybe better) add a flag to shuffle_seeds_challonge that will sort the players by garPR before randomizing.

**Comment by akbiggs** [comment]
Good idea, I'll do this but from garpr_seeds_challonge.py since shuffling should happen after ranking people by GaR PR, not before.

**Comment by akbiggs** [comment]
You can now pass `--shuffle` to `garpr_seeds_challonge.py` to shuffle the seeds after they've been seeded by gaR PR.
